2023-06-12 11:36:13,006 ERROR: Exception on /view [GET] [in /home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/timo/miniconda3/envs/archpy_env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/timo/Documents/Prototype/app/routes.py", line 206, in view
    realization_id = min(realization_id, d-1)
  File "/home/timo/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'output/2/2ba3904e-0904-11ee-9840-a45e60d3a055/realizations.npy'
2023-06-12 11:51:42,137 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:46]
2023-06-12 19:52:53,991 INFO: Application [in /home/timo/Documents/Prototype/app/__init__.py:46]
2023-06-25 09:13:52,070 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 09:14:08,647 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 09:14:59,104 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 09:15:20,841 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 09:17:56,275 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 13:25:51,054 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 13:26:57,906 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 13:28:46,692 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 13:30:30,573 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 13:56:34,073 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 13:59:25,041 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:04:24,391 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:07:56,167 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:16:22,827 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:18:08,345 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:28:44,270 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:31:59,535 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:39:11,199 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:41:23,693 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:51:40,848 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 14:55:01,144 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 15:28:14,070 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
2023-06-25 15:28:26,315 ERROR: Exception on /register [GET] [in C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\routes.py", line 134, in register
    return render_template('register.html', title='Register', form=form)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\templates\register.html", line 55, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2023-06-25 15:28:42,405 ERROR: Exception on /register [GET] [in C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\routes.py", line 134, in register
    return render_template('register.html', title='Register', form=form)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\kcost\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\templates\register.html", line 55, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2023-06-25 15:29:16,757 INFO: Application [in C:\Users\kcost\Documents\Master\Cours\R_DWorkShop\ArchPy\app\__init__.py:46]
